// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type ScheduleItemsCategory string

const (
	ScheduleItemsCategorySightseeing   ScheduleItemsCategory = "sightseeing"
	ScheduleItemsCategoryRestaurant    ScheduleItemsCategory = "restaurant"
	ScheduleItemsCategoryCafe          ScheduleItemsCategory = "cafe"
	ScheduleItemsCategoryAccommodation ScheduleItemsCategory = "accommodation"
	ScheduleItemsCategoryShopping      ScheduleItemsCategory = "shopping"
)

func (e *ScheduleItemsCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScheduleItemsCategory(s)
	case string:
		*e = ScheduleItemsCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for ScheduleItemsCategory: %T", src)
	}
	return nil
}

type NullScheduleItemsCategory struct {
	ScheduleItemsCategory ScheduleItemsCategory `json:"schedule_items_category"`
	Valid                 bool                  `json:"valid"` // Valid is true if ScheduleItemsCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScheduleItemsCategory) Scan(value interface{}) error {
	if value == nil {
		ns.ScheduleItemsCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScheduleItemsCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScheduleItemsCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScheduleItemsCategory), nil
}

type Day struct {
	ID     string    `json:"id"`
	TripID string    `json:"trip_id"`
	Date   time.Time `json:"date"`
}

type ScheduleItem struct {
	ID           string                `json:"id"`
	DayID        string                `json:"day_id"`
	Time         string                `json:"time"`
	LocationName string                `json:"location_name"`
	DisplayName  string                `json:"display_name"`
	Category     ScheduleItemsCategory `json:"category"`
	Notes        string                `json:"notes"`
	X            int32                 `json:"x"`
	Y            int32                 `json:"y"`
	GeoName      sql.NullString        `json:"geo_name"`
	Lat          sql.NullFloat64       `json:"lat"`
	Lng          sql.NullFloat64       `json:"lng"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
}

type Trip struct {
	ID          string         `json:"id"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	Title       string         `json:"title"`
	StartDate   time.Time      `json:"start_date"`
	EndDate     time.Time      `json:"end_date"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type User struct {
	ID          string         `json:"id"`
	Provider    string         `json:"provider"`
	ProviderUid string         `json:"provider_uid"`
	DisplayName string         `json:"display_name"`
	Email       sql.NullString `json:"email"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	CreatedAt   time.Time      `json:"created_at"`
}
