// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
)

type Querier interface {
	CreateDay(ctx context.Context, arg CreateDayParams) error
	CreateItem(ctx context.Context, arg CreateItemParams) error
	CreateTrip(ctx context.Context, arg CreateTripParams) error
	DeleteItem(ctx context.Context, id string) error
	DeleteTrip(ctx context.Context, id string) error
	GetDayByTripAndDate(ctx context.Context, arg GetDayByTripAndDateParams) (string, error)
	GetItem(ctx context.Context, id string) (GetItemRow, error)
	GetTrip(ctx context.Context, id string) (GetTripRow, error)
	ListDaysByTrip(ctx context.Context, tripID string) ([]ListDaysByTripRow, error)
	ListItemsByTrip(ctx context.Context, tripID string) ([]ListItemsByTripRow, error)
	// Trip CRUD (P1). sqlc.arg로 명명 파라미터 사용.
	ListTrips(ctx context.Context) ([]ListTripsRow, error)
	NextSortOrder(ctx context.Context, dayID string) (int64, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) error
	UpdateItemOrder(ctx context.Context, arg UpdateItemOrderParams) error
	UpdateTripTitle(ctx context.Context, arg UpdateTripTitleParams) error
}

var _ Querier = (*Queries)(nil)
