// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
)

type Querier interface {
	CountTrips(ctx context.Context) (int64, error)
	// P0 시작 쿼리 (sqlc 파이프라인 검증용). CRUD는 P1에서 확장.
	HealthCheck(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
