// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
)

const countTrips = `-- name: CountTrips :one
SELECT COUNT(*) AS total FROM trips
`

func (q *Queries) CountTrips(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTrips)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const healthCheck = `-- name: HealthCheck :one

SELECT 1 AS ok
`

// P0 시작 쿼리 (sqlc 파이프라인 검증용). CRUD는 P1에서 확장.
func (q *Queries) HealthCheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, healthCheck)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
